### ISSUE TITLE
Sometimes publish does not get it right

### ISSUE THREAD

**Issue by MFHuniovi** [noelex/rclnet#10]
I am creating an API to publish to "/goal_pose" but I don't understand why sometimes it fails to publish and nothing happens while the task is being completed correctly. 

```

public static bool SetGoalPose(float x1, float y1, float orientation)
{
  ILogger logger = LoggerHelper.Logger;
  bool result = false;
  try
  {
//ros2node only generates rclContext
    using (Ros2Node ros2Node = new Ros2Node(NODE_NAME))
    {
		PoseStamped poseStamped = new PoseStamped(new Header(new ROS2Messages.Builtin.Time(DateTime.UtcNow.Second, (uint)DateTime.UtcNow.Nanosecond)));
	    poseStamped.Pose.Position.X = x1;
	    poseStamped.Pose.Position.Y = y1;
	    poseStamped.Pose.Orientation = CalculateQuaternionRos(orientation);
	    poseStamped.Header.FrameId = "map";
		if (ros2Node == null)
		{
		  return false;
		}
		ValueTask valueTask = ros2Node.PublishAsync<PoseStamped>(poseStamped);
		bool complete = valueTask.AsTask().Wait(WAIT_TIMEOUT);
		if (!complete)
		{
		  throw new Exception($"API TIME OUT: [{WAIT_TIMEOUT}]");
		}
		if (valueTask.IsCompletedSuccessfully)
		{
		  logger.LogInformation("SetGoalPose => Service call finished with [IsCompletedSuccessfully]");
		  return true;
		}                                                            
		else if (valueTask.IsCompleted)                              
		{                                                            
		  logger.LogInformation("SetGoalPose => Service call finished with [IsCompleted]");
		  result = true;
		}
		else if (valueTask.IsFaulted)
		{
		  logger.LogInformation("SetGoalPose => Service call finished with [IsFaulted]");
		  result = false;
		}
		else if (valueTask.IsCanceled)
		{
		  logger.LogInformation("SetGoalPose => Service call finished with [IsCanceled]");
		  result = false;
		}
		else
		{
		  logger.LogInformation("SetGoalPose => Service call finished with unknow state");
		  result = false;
		}
    }
  } catch (Exception e)
  {
    logger.LogError("SetGoalPose => Exception setting goal pose [{0}]",e.Message);
    throw new Exception($"SetGoalPose[{NODE_NAME}] => See the logs. Exception [{e.Message}]", e);
  }
  return result;
}


//method from Ros2Node
  public async ValueTask PublishAsync<T>(T aMessage)
  {
    try
    {
      _theLogger.LogInformation("PublishAsync[{0}] => Starting publisher [{1}]", _theName, _theTopicName);
      await _thePublisher.PublishAsync(aMessage);
      _theLogger.LogInformation("Publish[{0}] => Publisher's inner task finished", _theName);
    }
    catch (Exception e)
    {
      throw new Exception($"Publish[{_theName}] => See the logs. Exception [{e.Message}]", e);
    }
    finally
    {
    }
  }
```
The logs always show "Service call finished with [IsCompletedSuccessfully]" but sometimes it doesn't publish anything because I'm looking with ros2 topic echo echo /goal_pose and it doesn't show what it supposedly just published. 
Does anyone know what could be going on here?
    
    
Update: (https://answers.ros.org/question/65774/publisher-not-publishing-on-topic/) I am reading that when working in c++ sometimes a publisher fails because it is not yet connected to the corresponding subscriber. Is it possible that my error is similar to that? Is it possible to wait for that connection?

**Comment by MFHuniovi** [comment]
Subscribers are active before creating the publisher. 
I managed to solve it by checking "if Subscribers > 1 then publish". I was testing the api on the /goal_pose topic that publishes the nav2 package and was having several more subscribers echoed by me (ros2 topic echo). What I noticed is that now it publishes but only 1 or 2 subscribers get to receive that information because it takes time to create that communication channel between publish and subscriber. I still have to modify the QoS to see if putting "durability" in "transient local" even if a subscriber creates the channel later than it is published can this subscriber receive the information. 

Do you think the solution I made based on the link I mentioned in the original post is a good one or would it be better to modify the "durability"?

**Comment by noelex** [comment]
I not quite sure about what you want to achieve here. Publishers shouldn’t bother whether there’s any subscriber or not, that’s how the pub/sub model works. 

And if you’re trying to send goal pose messages to nav2’s `bt_navigator`, the default QoS setting should work just fine.

Could you post a minimal repro project so I can take a look?

**Comment by MFHuniovi** [comment]
Sorry for the late reply

I have created a small project and run on a docker but it does not happen the same as my real environment which is communication from my pc to a robot. Even so from the docker I have replicated that there were 2 subscribers (create a basic subscriber node that prints information with the same behavior as a call to topic echo) and sometimes it only writes the message to 1 subscriber. The api code I am using is the following one

```
[HttpPost("SetGoalPoseUsing/{x}/{y}/{orientation}")]
public void SetGoalPoseUsing(float x, float y, float orientation)
{
  _logger.LogInformation($"SetGoalPoseUsing x:{x} y:{y} orientation:{orientation}");
  PoseStamped msg = CreatePoseStamped(x, y, orientation);
  using (RclContext ctx = new RclContext())
  {
    using (IRclNode node = ctx.CreateNode("API_node_with_using"))
    {
      using (IRclPublisher<PoseStamped> publisher = node.CreatePublisher<PoseStamped>("goal_pose"))
      {
        _logger.LogInformation($"SetGoalPoseUsing subscribers before publish [{publisher.Subscribers}]");
        publisher.Publish(msg);
        _logger.LogInformation($"SetGoalPoseUsing subscribers after publish [{publisher.Subscribers}]");
      }
    }
  }
}
```

In the following image you can see the API call with curl. The api log. The log of a subscriber node and the log of a call with ros2 topic echo.

![githubRclNet](https://github.com/noelex/rclnet/assets/71136753/3b7c9e55-e36a-44b5-96b4-47755abee06f)



To avoid this I do what I put in the original post where I saw in the ros forum that they check the number of subscribers before posting. As my goal is similar to publish only once I solved it that way for now although I know that a publisher should not care if someone subscribes or not as long as there is already a subscriber. 

You mentioned QoS but I have not been able to implement the "latch" in the publisher as mentioned in the ros documentation (https://wiki.ros.org/roscpp/Overview/Publishers%20and%20Subscribers 1.2 Publisher Options).

**Comment by noelex** [comment]
Thanks for the code. The code you posted is recreating `RclContext`, `IRclNode` and `IRclPublisher` in each request. This might be problematic because you’ll end up with creating and destroying event loop thread for each request.

Also, at the time you dispose the `IRclPublisher` object, the message you previously published may have not yet been sent to the wire, as the publish operation may happen asynchronously, depending on the RMW implementation you use.

Could you please try to see whether reusing  a single `RclContext`, `IRclNode` and `IRclPublisher` for all requests works for you?

**Comment by MFHuniovi** [comment]
If I create an RCLContext singleton it works better and rarely fails. Now, I need this for a debix board (it's like an arduino) and I'm worried about the processing of the board itself that's why I use so many using. If I do the publishAsync it fails 9/10 (no one is waiting) if I do the publish it fails 1/100 (after many calls it fails 1 or 2 times only with independent containers on the same local network now well in the real scanner they are on different machines this can increase).
Thanks for the advice to use a single RCLContext.
Finally, don't you think it's ok to use a subscriptions < 1?

**Comment by noelex** [comment]
Glad it worked for you. I'm closing this for now. Please reopen if you have further questions.
