### ISSUE TITLE
Can't avoid exceptions running examples from Visual Studio

### ISSUE THREAD

**Issue by sedwick2048** [noelex/rclnet#13]
I can build the C:\dev\rclnet-1.3.1\examples\RclExamples.sln solution in Visual Studio 2022, but setting the starting project to fake_clock and running in Debug mode, the following line in C:\dev\rclnet-1.3.1\src\Rcl.NET\RclContext.cs (#30) gets the following exception:

`private SpinLock _handleLock = new(), _callbackLock = new();`

System.TypeInitializationException: 'The type initializer for 'Rcl.RclContext' threw an exception.'
DllNotFoundException: Unable to load DLL 'rcutils' or one of its dependencies: The specified module could not be found. (0x8007007E)
This exception was originally thrown at this call stack:
    System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(string, System.Reflection.Assembly, System.Runtime.InteropServices.DllImportSearchPath?, bool) in NativeLibrary.cs

I then try to add solution or project references to one of these DLLs:

- C:\dev\ros2_humble\ros2-windows\bin\rcutils.dll
- C:\dev\ros2_humble\bin\rcutils.dll

...but each time I browse to the DLL and hit "OK", I'm told the reference is invalid or unsupported.  How can I fix this?  Thanks...

**Comment by noelex** [comment]
Please refer to [this discussion](https://github.com/noelex/rclnet/discussions/3).

**Comment by sedwick2048** [comment]
OK, so I modified C:\dev\rclnet-1.3.1\examples\fake_clock\Properties\launchSettings.json to be this:

```
{
  "profiles": {
    "Windows": {
      "commandName": "Project",
      "environmentVariables": {
        "ROS_DISTRO": "humble",
        "ROS_LOCALHOST_ONLY": "0",
        "ROS_PYTHON_VERSION": "3",
        "ROS_VERSION": "2",
        "PATH": "C:\\dev\\ros2_humble\\ros2-windows\\bin;C:\\Program Files\\OpenSSL-Win64\\bin;C\\ProgramData\\chocolatey\\lib\\tinyxml2\\lib",
        "AMENT_PREFIX_PATH": "C:\\dev\\ros2_humble\\ros2-windows"
      }
    }
  }
}
```

And now when I run, it doesn't flash that error anymore, but it also doesn't hit any breakpoints or "catch" blocks I added to C:\dev\rclnet-1.3.1\examples\fake_clock\Program.cs.  The console window is up for a couple of seconds before disappearing, right after it flashes this:
![RMW error running ROS2 example fake_clock](https://github.com/noelex/rclnet/assets/165824359/706df67c-2a67-4db5-bdef-037668fba9fb)
The C:\ci\ws\src\ros2\... path is not on my machine, and there is no rmw_implementation_identifier_check.c file.  Thanks in advance for anything that can get me unstuck...

**Comment by noelex** [comment]
Did you follow the instructions to install ROS2 and its dependencies, especially OpenSSL? You also need to specify the installation directory in `PATH`.

**Comment by sedwick2048** [comment]
C:\dev\ros2_humble was where I installed ROS2.  I tried removing `\\ros2-windows` from `PATH`, but no effect. I can enter each of the following commands into their own command windows and witness communication, so I must have an installation (I'm pretty certain I followed the [instructions](https://docs.ros.org/en/humble/Installation/Windows-Install-Binary.html)):

```
ros2 run demo_nodes_cpp talker
ros2 run demo_nodes_py listener
```

**Comment by sedwick2048** [comment]
I assigned my launchSettings.json settings to match their corresponding environment variables (as shown in the command window after entering "set"), and now fake_clock runs and publishes.
