### ISSUE TITLE
No Rosidl.Messages.Rosbag2StorageMcapTestdata.BasicIdl for ComplexMsgDependsOnIdl

### ISSUE THREAD

**Issue by sedwick2048** [noelex/rclnet#14]
I ran ros2cs on my C:\dev\SmplROS2dNET2\ros2cs.spec without any package exclusions.  After it processed 32 packages and 287 message definitions, VS2022 gave me 430+ errors of type "CS0227 Unsafe code may only appear if compiling with /unsafe".  I took the quick action's advice to allow the project to use unsafe code, but now I still have 5 errors of "CS0234 The type or namespace name 'BasicIdl' does not exist in the namespace 'Rosidl.Messages.Rosbag2StorageMcapTestdata' (are you missing an assembly reference?)".  All 5 errors are in C:\dev\SmplROS2dNET2\Rosbag2StorageMcapTestdata\Messages\ComplexMsgDependsOnIdl.cs, which I assume it generated from C:\dev\ros2_humble(\ros2-windows)\share\rosbag2_storage_mcap_testdata\msg\ComplexMsgDependsOnIdl.idl.  IntelliSense confirms that Rosbag2StorageMcapTestdata in fact does not have BasicIdl as a member, even with my project including the Rcl.NET (1.3.2) package.  I may be able to remove C:\dev\SmplROS2dNET2\Rosbag2StorageMcapTestdataC:\dev\SmplROS2dNET2\Rosbag2StorageMcapTestdata from my project, but this should probably be addressed nonetheless.  Thanks...

**Comment by noelex** [comment]
rclnet does not support IDLs currently. Please exclude the offending package from code generation.
