### ISSUE TITLE
Unable to see node from ROS2 CLI

### ISSUE THREAD

**Issue by carsonloyaltrimble** [noelex/rclnet#17]
Hi there,

First this is a great library and thanks for the hard work here. 

I am able to create a new .NET 7 application and create context, node and publisher to publish async while my app is running. My issue is that I am not able to see the node listed in the command line ros2 interface using the command: `ros2 node list`

For the examples, the topic and data do show up as expected.

Is this intended behavior? I do not think it causes a huge issue more that it is very difficult to debug the system with large amounts of nodes running. Would love to help dig into this if needed and thanks again!

Code:
```csharp
 private async void SpinNode()
 {
     await using var ctx = new RclContext();
     using var node = ctx.CreateNode("turtle_circling");
     using var pub = node.CreatePublisher<Twist>("/turtle1/cmd_vel");

     var twist = new Twist(
         linear: new(x: 3.0f),
         angular: new(z: 1.8f)
     );

     while (!cts.IsCancellationRequested)
     {
         Debug.WriteLine("Publishing! ros2 publisher");
         await pub.PublishAsync(twist);
         await Task.Delay(1000, cts.Token);
     }
 }
```

![image](https://github.com/noelex/rclnet/assets/152992279/e04798fb-f070-4616-8fa0-a69299c60f6d)

**Comment by noelex** [comment]
Could you please try running the `graph_monitor` example first and then start your node and see if `graph_monitor` can receive node online events?

**Comment by stewpend0us** [comment]
For what it's worth...this example does seem to work fine in linux. Only edits I made were ```async Task``` rather than ```async void``` because I needed something to ```await``` in Main.

**Comment by stewpend0us** [comment]
I have had problems similar to this when the executable is being run as root instead of a user. I'm not sure if there is a similar thing in Windows or not.

**Comment by carsonloyaltrimble** [comment]
> Could you please try running the `graph_monitor` example first and then start your node and see if `graph_monitor` can receive node online events?

Will do this and report back! Also will try running as user instead.

**Comment by carsonloyaltrimble** [comment]
> I have had problems similar to this when the executable is being run as root instead of a user. I'm not sure if there is a similar thing in Windows or not.

I am on windows and it appears there is a similar-ish behavior. When I build and run the project from Visual Studio 2022 in Windows then I am not able to see the node using `ros2 node list` in other terminals. If I manually run the build executable in a fresh command prompt then I am able to see it as normal. Any thoughts on this @noelex

**Comment by noelex** [comment]
> If I manually run the build executable in a fresh command prompt then I am able to see it as normal.

Looks like an environment issue. Does removing `launchSettings.json` and launching Visual Studio from a command prompt with `setup.bat` sourced work for you?

**Comment by carsonloyaltrimble** [comment]
It looks like this is related to the env config in Visual Studio. It does not seem to cause any issues so I am happy to close this for now since that seems to be the root cause. Thanks everyone! @noelex great repo!
